{{- if or .Values.deployment.serviceAccount.create .Values.deployment.serviceAccount.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kong.serviceAccountTokenName" . }} 
  namespace: {{ template "kong.namespace" . }}
  annotations:
    kubernetes.io/service-account.name: {{ template "kong.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- if .Values.deployment.serviceAccount.enableKumaPatch }}
---
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: {{ template "kong.fullname" . }}-kuma-patch
  namespace: kuma-system
spec:
  sidecarPatch:
    - op: add
      path: "/volumeMounts"
      value: '[]'
    - op: add
      path: "/volumeMounts/-"
      value: '{ "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount/", "name":"{{ template "kong.serviceAccountTokenName" . }}", "readOnly": true }'
{{- end }}
{{- end }}
